TOPページの作成
saitokazumasa/tabisketch pull request #100
Opened 2024-11-22 01:53 UTC by BruinJr

## 概要

close #18 

- TOPページの作成
- TOPの画像を10秒ごとに変わるように
- レスポンシブ

### スクリーンショット

スマホ画面
![image](https://github.com/user-attachments/assets/193204fa-4b53-49f0-af00-b040e4890ed1)
pc画面はデカ過ぎたのでか割愛

2024-11-22 01:55 UTC, saitokazumasa commented
PC画面のスクショ割愛しないで

2024-11-22 01:58 UTC, ken-250 commented on src/main/resources/templates/top.html
> +        </p>
これ中央寄せになってないの気になる

2024-11-22 02:03 UTC, t-dounoma commented
sp版の左右のテキストの余白もうちょとあってもいいかなっておもた

2024-11-22 02:17 UTC, saitokazumasa requested changes

2024-11-22 02:17 UTC, saitokazumasa commented on src/main/resources/templates/fragment/script.html
> +</th:block>
このjsってtopページ以外にも使うの？
使わないなら共通に書く必要はないと思われ

2024-11-22 02:18 UTC, BruinJr commented on src/main/resources/templates/fragment/script.html
> +</th:block>
top以外で使わないけど一応入れました。
変更します。

2024-11-22 02:35 UTC, saitokazumasa requested changes

2024-11-22 02:35 UTC, saitokazumasa commented on src/main/resources/static/js/top.js
> +}, 10000); // 10秒ごとに切り替え
```suggestion
class ImageUrls {
    urls = [
        '/images/top1.png',
        '/images/top2.png',
        '/images/top3.png',
        '/images/top4.png',
        '/images/top5.png',
        '/images/top6.png',
    ];
    currentIndex = -1;

    nextUrl() {
        const nextIndex = this.currentIndex + 1;
        this.currentIndex = nextIndex >= this.urls.length? 0 : nextIndex;
        return this.urls[this.currentIndex];
    }
}

const imagesElement = document.getElementById('images');
const imageUrls = new ImageUrls();

function nextImage() {
    imagesElement.src = imageUrls.nextUrl();
}

setInterval(() => nextImage(), 10000);
```

ごめんね、色々言いたいことがあります。

### 1. なるべくコメントが無くてもわかるコードを書くことを意識する
コメントがあると読むコード量が増えるため、なるべくない方が良い。
しかし、あった方がわかりやすいのも事実。
よって、本当に必要なところにだけコメントをし、
なるべくコメントしなくてもわかりやすいコードを書くようにすると良い。

例) コメントを付けるのではなく、関数化して適切な名前を付ければ、名前自体がコメントと同等の役割をする。
```
setInterval(() => {
    // 次の画像に切り替える
    currentIndex = (currentIndex + 1) % images.length;

    ~~省略~~
}
```
```
setInterval(() => {
    nextImage();

    ~~省略~~
}
```

### 2. 変数のスコープは狭くする
クラス化してスコープを狭くすることで、
意図せず書き換えたり、アクセスしたりするのを防げる。

ついでに、やっていることを関数化して適切な名前を付ければ
コメントなくして、「これは image の src に次のイメージURLをセットしているんだな」とわかりやすくなる。
```
imagesElement.src = imageUrls.nextUrl();
```

### 3. インクリメントが無限に増えそう
```
currentIndex = (currentIndex + 1) % images.length;
```
この書き方初めて見た。
綺麗でいいね！

ただ、僕の考え方が正しければ、ページを表示し続けているとindexが無限に増えることになりそう。

2024-11-22 02:47 UTC, saitokazumasa commented
あとmainのマージは都度してね。
少なくともPRを出す前にマージしてください。

2024-11-22 03:38 UTC, BruinJr commented on src/main/resources/static/js/top.js
> +}, 10000); // 10秒ごとに切り替え
指摘ありがとう！
修正しました。
[3df6d19](https://github.com/saitokazumasa/tabisketch/pull/100/commits/3df6d196ce45ffd7458669b34617d5c6a7788160)

2024-11-22 03:39 UTC, BruinJr commented on src/main/resources/templates/fragment/script.html
> +</th:block>
topで呼び出すように修正しました。
[2ebb500](https://github.com/saitokazumasa/tabisketch/pull/100/commits/2ebb500e93c9fb7cbb51d9ab4856b77864d377a1)

2024-11-22 03:39 UTC, BruinJr commented on src/main/resources/static/images/top1.png
軽量化しました。
[486ac70](https://github.com/saitokazumasa/tabisketch/pull/100/commits/486ac70971d2262cef9b27b739f82bf568ab4f1f)

2024-11-25 00:35 UTC, saitokazumasa commented on src/main/resources/static/images/top1.png
あざまる

2024-11-25 00:35 UTC, saitokazumasa commented on src/main/resources/templates/fragment/script.html
> +</th:block>
あざまる

2024-11-25 00:39 UTC, saitokazumasa commented on src/main/resources/static/js/top.js
> +}, 10000); // 10秒ごとに切り替え
あざまる

2024-11-25 00:40 UTC, saitokazumasa approved these changes
よいかんじ
LGTM

2024-11-25 00:43 UTC, t-dounoma requested changes

2024-11-25 00:43 UTC, t-dounoma commented on src/main/resources/templates/top.html
> +        <p class="text-2xl hidden sm:block">「らくたび」はあなたの旅のお供です。</p>
たびすけっち

2024-11-25 00:43 UTC, t-dounoma commented on src/main/resources/templates/top.html
> +            「らくたび」はあなたの旅のお供です。
ここも

2024-11-25 00:46 UTC, BruinJr commented on src/main/resources/templates/top.html
> +        <p class="text-2xl hidden sm:block">「らくたび」はあなたの旅のお供です。</p>
変更しました。
[8751eb7](https://github.com/saitokazumasa/tabisketch/pull/100/commits/8751eb76cfe983396b187443bcda140dbce72114)

2024-11-25 00:47 UTC, BruinJr commented on src/main/resources/templates/top.html
> +            「らくたび」はあなたの旅のお供です。
変更しました。
[8751eb7](https://github.com/saitokazumasa/tabisketch/pull/100/commits/8751eb76cfe983396b187443bcda140dbce72114)

2024-11-25 00:48 UTC, t-dounoma approved these changes

2024-11-25 00:48 UTC, merged