各確認画面のデザイン作成
saitokazumasa/tabisketch pull request #103
Opened 2024-11-22 03:26 UTC by t-dounoma

## 概要

close #96

- 再送信ボタンが押された時の処理が未作成のためissueに追加予定
- 3ページ分の確認ページを作成しました
- 文言の変更などがあれば教えてください

### スクリーンショット

'メール送信確認(送信登録確認)'
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/c61260fc-e052-454e-8b7c-79b25fcc542c">
'メールアドレス編集(送信登録確認)'
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/1a2d716e-f805-476e-9119-a0059299c770">
'パスワードリセット(送信登録確認)'
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/f9a5e11f-95aa-43ff-8cbd-e07a447f9a5d">

2024-11-22 03:40 UTC, saitokazumasa requested changes

2024-11-22 03:40 UTC, saitokazumasa commented on src/main/resources/templates/user/create-confirm.html
URL変更に伴ってファイル名を変更したいです。`register/send`

2024-11-22 03:40 UTC, saitokazumasa commented on src/main/resources/templates/user/edit/mail-confirm.html
同様に。 `user/edit/mail-send` か `user/edit/mail/send`

2024-11-22 03:40 UTC, saitokazumasa commented on src/main/resources/templates/user/password-reset-confirm.html
同様に。 `password-reset/send`

2024-11-25 00:39 UTC, t-dounoma commented on src/main/resources/templates/user/create-confirm.html
ご確認のほどよろしくお願いいたします
b184d1eaacb00c30a4206e84cec218dcfe51ab48

2024-11-25 00:39 UTC, t-dounoma commented on src/main/resources/templates/user/edit/mail-confirm.html
ご確認のほどよろしくお願いいたします
b184d1eaacb00c30a4206e84cec218dcfe51ab48

2024-11-25 00:39 UTC, t-dounoma commented on src/main/resources/templates/user/password-reset-confirm.html
ご確認のほどよろしくお願いいたします
b184d1eaacb00c30a4206e84cec218dcfe51ab48

2024-11-25 01:51 UTC, ishiki11 approved these changes
デザインは大丈夫です

2024-11-25 03:42 UTC, saitokazumasa approved these changes
あざまLGTM

2024-11-25 03:42 UTC, merged