PlanListControllerの作成
saitokazumasa/tabisketch pull request #116
Opened 2024-11-25 03:28 UTC by imanoari

## 概要

close #115 

- プラン一覧のコントローラーを作成
- PlanListControllerのテストを作成
- テスト通るか確認してほしいです
### スクリーンショット

割愛

2024-11-25 03:34 UTC, saitokazumasa requested changes
後 PR の書き方についてなのですが、
要望と変更内容を一緒に書かず、見る人がわかりやすい書き方を心がけましょう。
![image](https://github.com/user-attachments/assets/c66cd74d-c834-4ee8-92c1-994eae5895fe)

2024-11-25 03:34 UTC, saitokazumasa commented on src/main/java/com/tabisketch/controller/PlanListController.java
> +public class PlanListController {
動詞 + 名詞 + Controller の形が良いです。

2024-11-25 03:34 UTC, saitokazumasa commented on src/main/java/com/tabisketch/controller/PlanListController.java
> +    public String planList() {
get で

2024-11-25 03:34 UTC, saitokazumasa commented on src/main/java/com/tabisketch/controller/PlanListController.java
> +    @GetMapping()
`()` なしで

2024-11-25 03:36 UTC, saitokazumasa commented
![image](https://github.com/user-attachments/assets/4a0b4f75-a0a5-4f9c-a0e0-a65bc75da9a8)
前も行ったけど、ブランチ名見づらいです。
ハイフン付けるんだ

2024-11-25 03:54 UTC, ken-250 requested changes

2024-11-25 03:54 UTC, ken-250 commented on src/test/java/com/tabisketch/controller/PlanListControllerTest.java
> +    public void test() throws Exception {
テストの関数名は日本語で。
他のテストだと `getが動作するか()` みたいな感じになってる。

2024-11-26 01:02 UTC, imanoari commented on src/main/java/com/tabisketch/controller/PlanListController.java
> +    @GetMapping()
修正しましたhttps://github.com/saitokazumasa/tabisketch/pull/116/commits/13ddd269991613dd5118ac32326a71b6ad043880

2024-11-26 01:05 UTC, imanoari commented on src/test/java/com/tabisketch/controller/PlanListControllerTest.java
> +    public void test() throws Exception {
間違えてcontroller名の修正と一緒にコミットしましたごめんなさい
https://github.com/saitokazumasa/tabisketch/pull/116/commits/c9fe4aa981382eac255f2332662dab792affd383

2024-11-26 01:06 UTC, imanoari commented on src/main/java/com/tabisketch/controller/PlanListController.java
> +public class PlanListController {
テストの関数名の修正が一緒にあります…以後気を付けます
https://github.com/saitokazumasa/tabisketch/pull/116/commits/c9fe4aa981382eac255f2332662dab792affd383

2024-11-26 02:08 UTC, saitokazumasa commented on src/main/java/com/tabisketch/controller/PlanListController.java
> +public class PlanListController {
あざまる

2024-11-26 02:08 UTC, saitokazumasa commented on src/main/java/com/tabisketch/controller/PlanListController.java
> +    public String planList() {
あざまる

2024-11-26 02:08 UTC, saitokazumasa commented on src/main/java/com/tabisketch/controller/PlanListController.java
> +    @GetMapping()
あざまる

2024-11-26 02:09 UTC, saitokazumasa approved these changes
おっけーLGTM

2024-11-27 00:35 UTC, ken-250 approved these changes
確認しました👍

2024-11-27 00:35 UTC, merged