ユーザー編集のコントローラー作成
saitokazumasa/tabisketch pull request #140
Opened 2024-11-29 03:18 UTC by imanoari

## 概要

- controller作成
- テストデータ作成

### スクリーンショット

2024-11-29 04:00 UTC, saitokazumasa requested changes

2024-11-29 04:00 UTC, saitokazumasa commented on src/main/java/com/tabisketch/controller/EditUserController.java
> +        User item = new User();
item って何？

2024-11-29 04:00 UTC, saitokazumasa commented on src/main/java/com/tabisketch/controller/EditUserController.java
> +        item.setMail("user@example.com");
何でここでセットしているの？

2024-11-29 04:02 UTC, saitokazumasa requested changes

2024-11-29 04:02 UTC, saitokazumasa commented on src/test/java/com/tabisketch/controller/EditUserControllerTest.java
> +    public void getが動作するか() throws Exception {
throws Exception しないで。
try catch でとって、エラーがあったらテストが通らないようにして欲しい

2024-12-02 00:51 UTC, saitokazumasa commented on src/test/java/com/tabisketch/controller/EditUserControllerTest.java
> +    public void getが動作するか() throws Exception {
この書き方で統一することに変更。
そのためOK

2024-12-02 01:00 UTC, imanoari commented on src/main/java/com/tabisketch/controller/EditUserController.java
> +    }
final付けました
https://github.com/saitokazumasa/tabisketch/pull/140/commits/f6970a36c519918778eea6139eb286857b421bc5

2024-12-02 01:10 UTC, imanoari commented on src/main/java/com/tabisketch/controller/EditUserController.java
> +        item.setMail("user@example.com");
すみません。仮の処理で現在手動でメールアドレスをセットしています。後ほどMapperを追加しユーザー情報の取得する処理に書き換えます。コメント追加しました
https://github.com/saitokazumasa/tabisketch/pull/140/commits/8601b74982be60be360e065ef30a1fe2b8c0cf21

2024-12-02 02:02 UTC, saitokazumasa commented on src/main/java/com/tabisketch/controller/EditUserController.java
> +    }
OK

2024-12-02 02:04 UTC, saitokazumasa commented on src/main/java/com/tabisketch/controller/EditUserController.java
> +        item.setMail("user@example.com");
`todo 仮の処理` だと仮の処理を書くことがtodoっぽいです。
やるなら、`todo 以下は仮のため、後で書き換える` などが良いです。

2024-12-02 02:51 UTC, imanoari commented on src/main/java/com/tabisketch/controller/EditUserController.java
> +        item.setMail("user@example.com");
コメント編集しておきます

2024-12-02 02:53 UTC, imanoari commented on src/main/java/com/tabisketch/controller/EditUserController.java
> +        item.setMail("user@example.com");
編集しました
https://github.com/saitokazumasa/tabisketch/pull/140/commits/102bcb241b719a78b93bd22d4c513021fb4526a4

2024-12-02 02:58 UTC, saitokazumasa commented on src/main/java/com/tabisketch/controller/EditUserController.java
> +        item.setMail("user@example.com");
OK

2024-12-02 02:58 UTC, saitokazumasa commented on src/main/java/com/tabisketch/controller/EditUserController.java
> +        User item = new User();
仮の処理とのことなためOK

2024-12-02 02:58 UTC, saitokazumasa approved these changes
LGTM

2024-12-02 02:59 UTC, merged