目的地追加時にフラグメント追加
saitokazumasa/tabisketch pull request #141
Opened 2024-11-29 03:22 UTC by ishiki11

## 概要

close #122 #124 

- 目的地追加formのsubmitイベントで非同期処理（`/fragment/modal/places`に）
- `/fragment/modal/places`をWebSecurityで通したい
- 非同期処理でフラグメント呼び出し
- フラグメントを呼び出し `id : desination`の子要素に入れてる
- 呼び出したフラグメントに対してautocompleteのapiをセット（`initalizeModal()`の`setupAutocomplete()`）
- `autocomple.js`のリファクタリング

### スクリーンショット

ローカルで作った非同期処理のコントローラ
![image](https://github.com/user-attachments/assets/5bc8906b-48fb-4dcc-87e3-d273ddefb9c3)

![image](https://github.com/user-attachments/assets/226d6267-6d83-4145-9e09-ed6618d0e3c1)

2024-11-29 03:37 UTC, t-dounoma requested changes

2024-11-29 03:37 UTC, t-dounoma commented on src/main/resources/static/js/modal.js
> +// 初回のフォームイベント登録
このコメントなくてもわかるっすよ

2024-11-29 04:02 UTC, saitokazumasa requested changes
後ほど詳細にレビューするので一旦止めます。

2024-12-02 01:37 UTC, saitokazumasa requested changes
まずはautocompleteのレビューです。
最終的に以下のように自分だったらするかな。
（動確はしてないから良い感じに書き換えて）

あと、AutoComplete っておそらくGoogle APIのなんかだと思うんだけど、
そのままの名前だと何か全然わからないのでコメントとか付けると良き。

もしくは独自のわかりやすい名前にしてあげると良いと思う。
```
class SessionToken {
    #value;

    constructor() {
        this.#value = new google.maps.places.AutocompleteSessionToken();
    }

    value() {
        return this.#value;
    }
}

/**
 * Google の AutoComplete (いい感じにコメント書き換えて)
 */
class AutoComplete {
    #value;
    #inputElement;

    constructor(inputElement) {
        this.#inputElement = inputElement;

        this.#value =
            new google.maps.places.Autocomplete(inputElement, {
                types: ['establishment'],
                componentRestrictions: {country: ['JP']},
                fields: ['place_id', 'geometry', 'name'],
            });

        const sessionToken = new SessionToken();
        this.#value.setOptions({sessionToken: sessionToken.value()});
        this.#value.addListener('place_changed', () => this.onPlaceChanged());
    }

    onPlaceChanged() {
        const place = this.#value.getPlace();

        if (!place.geometry()) {
            // TODO: この文言は別の場所にまとめた方が良い
            this.#inputElement.placeholder = '場所を入力して下さい';
            return;
        }

        this.#inputElement.value = place.name;

        const sessionToken = new SessionToken();
        this.#value.setOptions({sessionToken: sessionToken.value()});
    }
}

const initInstanceKeys = [
    'startPlace',
    'endPlace',
    'place1'
];

const autoCompletes = new Array(0);

function init() {
    initInstanceKeys.forEach(key => {
        const inputElement = document.getElementById(key);
        if (!inputElement) return;

        const autoComplete = new AutoComplete(inputElement);
        autoCompletes.push(autoComplete);
    });
}

init();
```

2024-12-02 01:37 UTC, saitokazumasa commented on src/main/resources/static/js/autocomplete.js
> +let sessionManager;
これ function 内でしか値入れてないから生焼けオブジェクトになる可能性がかなり高いためNG
また、AutoCompleteでしか使っていないのなら、AutoComplete自体をクラスにしてしまって、そこに隠してしまう方が良い。

2024-12-02 01:37 UTC, saitokazumasa commented on src/main/resources/static/js/autocomplete.js
> +    ];
```suggestion
    const initInstanceKeys = [
        'startPlace',
        'endPlace',
        'place1'
    ];
```
この変数はinstanceっていうよりidの配列だから instanceIds の方が良き。
また、id っていうより key かなと思った。
id だと項番のイメージ。

2024-12-02 01:37 UTC, saitokazumasa commented on src/main/resources/static/js/autocomplete.js
> +        }
```suggestion
        if (!inputElement) return;
        
        setupAutocomplete(inputElement);
```
ネストはあればあるほど見づらく、なければないほど見やすくなるため、
いかにネストしないかを考えると良き

2024-12-02 01:37 UTC, saitokazumasa commented on src/main/resources/static/js/autocomplete.js
>      } else {
この辺りも同じく、早期リターンでネストしないようにした方が良き

2024-12-02 02:43 UTC, t-dounoma requested changes
今更なんですけど、出発地点と終了地点だけyの中央揃えがないんで追加お願いします
![image](https://github.com/user-attachments/assets/9d849e7d-bc3c-4da6-b711-1fe337d6600c)

2024-12-02 02:55 UTC, saitokazumasa commented on src/main/resources/static/js/autocomplete.js
> +    ];
ごめん、もしかしてidってつけてたのってHTMLのidに乗っ取って付けてた感じ？
それならidでいいかも

2024-12-02 04:22 UTC, ishiki11 commented
> まずはautocompleteのレビューです。 最終的に以下のように自分だったらするかな。 （動確はしてないから良い感じに書き換えて）
> 
> あと、AutoComplete っておそらくGoogle APIのなんかだと思うんだけど、 そのままの名前だと何か全然わからないのでコメントとか付けると良き。
> 
> もしくは独自のわかりやすい名前にしてあげると良いと思う。
> 
> ```
> class SessionToken {
>     #value;
> 
>     constructor() {
>         this.#value = new google.maps.places.AutocompleteSessionToken();
>     }
> 
>     value() {
>         return this.#value;
>     }
> }
> 
> /**
>  * Google の AutoComplete (いい感じにコメント書き換えて)
>  */
> class AutoComplete {
>     #value;
>     #inputElement;
> 
>     constructor(inputElement) {
>         this.#inputElement = inputElement;
> 
>         this.#value =
>             new google.maps.places.Autocomplete(inputElement, {
>                 types: ['establishment'],
>                 componentRestrictions: {country: ['JP']},
>                 fields: ['place_id', 'geometry', 'name'],
>             });
> 
>         const sessionToken = new SessionToken();
>         this.#value.setOptions({sessionToken: sessionToken.value()});
>         this.#value.addListener('place_changed', () => this.onPlaceChanged());
>     }
> 
>     onPlaceChanged() {
>         const place = this.#value.getPlace();
> 
>         if (!place.geometry()) {
>             // TODO: この文言は別の場所にまとめた方が良い
>             this.#inputElement.placeholder = '場所を入力して下さい';
>             return;
>         }
> 
>         this.#inputElement.value = place.name;
> 
>         const sessionToken = new SessionToken();
>         this.#value.setOptions({sessionToken: sessionToken.value()});
>     }
> }
> 
> const initInstanceKeys = [
>     'startPlace',
>     'endPlace',
>     'place1'
> ];
> 
> const autoCompletes = new Array(0);
> 
> function init() {
>     initInstanceKeys.forEach(key => {
>         const inputElement = document.getElementById(key);
>         if (!inputElement) return;
> 
>         const autoComplete = new AutoComplete(inputElement);
>         autoCompletes.push(autoComplete);
>     });
> }
> 
> init();
> ```

2024-12-03 00:44 UTC, ishiki11 commented on src/main/resources/static/js/autocomplete.js
> +}
修正しました
[470a517](https://github.com/saitokazumasa/tabisketch/pull/141/commits/470a51788ddab85722a5c60e16d7ee0b8151e52a)

2024-12-03 00:45 UTC, ishiki11 commented on src/main/resources/static/js/modal.js
> +const placeNum = new PlaceNumManager();
修正しました
[0fe5a0b](https://github.com/saitokazumasa/tabisketch/pull/141/commits/0fe5a0b7f5dba91212b6df63ddd5438819667824)

2024-12-03 00:45 UTC, ishiki11 commented
> 今更なんですけど、出発地点と終了地点だけyの中央揃えがないんで追加お願いします ![image](https://private-user-images.githubusercontent.com/101164515/391393601-9d849e7d-bc3c-4da6-b711-1fe337d6600c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxODY4NzEsIm5iZiI6MTczMzE4NjU3MSwicGF0aCI6Ii8xMDExNjQ1MTUvMzkxMzkzNjAxLTlkODQ5ZTdkLWJjM2MtNGRhNi1iNzExLTFmZTMzN2Q2NjAwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwMDQyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODMyZjI1YjdlOWJmN2YwZTBlMDQxM2JlZjdkODJmMGY4ZGE3ZjAyOWQ0ZDI4YjZmYTI1ODU4NmJlMzAzOWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4S5_6Rt1zX6_AGSfj3dOVN3fnF2RIRIbjBkaxLXywIY)

修正しました
[1c7e1d4](https://github.com/saitokazumasa/tabisketch/pull/141/commits/1c7e1d4e5a8b46356888bd32765205dd94772d23)

2024-12-03 00:47 UTC, t-dounoma approved these changes
確認しました
LGTM

2024-12-03 00:53 UTC, saitokazumasa commented on src/main/resources/static/js/autocomplete.js
> +}
サンクス！

2024-12-03 00:54 UTC, saitokazumasa commented on src/main/resources/static/js/autocomplete.js
> +let sessionManager;
ここで合わせて修正されているためOK
https://github.com/saitokazumasa/tabisketch/pull/141/commits/470a51788ddab85722a5c60e16d7ee0b8151e52a

2024-12-03 00:54 UTC, saitokazumasa commented on src/main/resources/static/js/autocomplete.js
> +        }
ここで合わせて修正されているためOK
https://github.com/saitokazumasa/tabisketch/pull/141/commits/470a51788ddab85722a5c60e16d7ee0b8151e52a

2024-12-03 01:02 UTC, saitokazumasa requested changes

2024-12-03 01:02 UTC, saitokazumasa commented on src/main/resources/static/js/modal.js
> +            const form = new ModalForm();
ちょっときつきつで見づらいかな
例えば、一つの項目ごとに区切って空白入れると見やすくなるかも
下は参考例だからいい感じに修正してね。
```
            const fragment = new Fragment();
            await fragment.initialize();

            if (!fragment.value()) {return;}

            const modal = new ModalElement();

            fragment.addFragment();
            modal.closeModal();
            placeNum.increment();

            const newModal = new ModalElement();
            const form = new ModalForm();
```

2024-12-03 01:02 UTC, saitokazumasa commented on src/main/resources/static/js/modal.js
> +InitModal();
これわざわざ関数にしなくてもいいんじゃない？

2024-12-03 01:02 UTC, saitokazumasa commented on src/main/resources/static/js/modal.js
> +const placeNum = new PlaceNumManager();
確認して新しくRV付けました。

2024-12-03 01:03 UTC, saitokazumasa commented on src/main/resources/static/js/modal.js
> +        }
ここで修正されたためOK
https://github.com/saitokazumasa/tabisketch/pull/141/commits/0fe5a0b7f5dba91212b6df63ddd5438819667824

2024-12-03 01:04 UTC, saitokazumasa commented on src/main/resources/static/js/modal.js
> +function initializeModal() {
ここで修正されたためOK
https://github.com/saitokazumasa/tabisketch/pull/141/commits/0fe5a0b7f5dba91212b6df63ddd5438819667824

2024-12-03 01:04 UTC, saitokazumasa commented on src/main/resources/static/js/modal.js
> +function initializeForm() {
ここで修正されたためOK
https://github.com/saitokazumasa/tabisketch/pull/141/commits/0fe5a0b7f5dba91212b6df63ddd5438819667824

2024-12-03 01:05 UTC, saitokazumasa commented on src/main/resources/static/js/modal.js
> +        setupAutocomplete(inputElement);
ここで修正されたためOK
https://github.com/saitokazumasa/tabisketch/pull/141/commits/470a51788ddab85722a5c60e16d7ee0b8151e52a
https://github.com/saitokazumasa/tabisketch/pull/141/commits/0fe5a0b7f5dba91212b6df63ddd5438819667824

2024-12-03 01:12 UTC, ishiki11 commented on src/main/resources/static/js/modal.js
> +    }
constructor で async 使って値入れたかったんだけど、できなくてこうなってた
なんか他の方法あったら教えてほしい
⇩参考
https://zenn.dev/katoaki/articles/2f23ec42de7f6b

2024-12-03 01:13 UTC, ishiki11 commented on src/main/resources/static/js/modal.js
> +            setTimeout(() => document.activeElement.blur(), 0)
外しました
[9841b58](https://github.com/saitokazumasa/tabisketch/pull/141/commits/9841b58b4693d490448bb3fe4612e5dec37f3bd7)

2024-12-03 01:14 UTC, ishiki11 commented on src/main/resources/static/js/modal.js
> +InitModal();
関数はずしました
[939845c](https://github.com/saitokazumasa/tabisketch/pull/141/commits/939845cb66207b37c4436bb83f2d23d28a638e81)

2024-12-03 01:17 UTC, saitokazumasa commented on src/main/resources/static/js/modal.js
> +    }
なるほど、確かにコンストラクタでawait/asyncはできない
う～ん、そうしたら `addFragment()` とか `value()` とか全ての関数の最初に
```
if (this.#value == null) throws new Error('このインスタンスは初期化されていません。initialize()をしてください。');
```
みたいなのを毎回付ければ一応バグ回避にはなるかなぁ。

2024-12-03 01:22 UTC, ishiki11 commented on src/main/resources/static/js/modal.js
> +    }
付けました
[5d074a6](https://github.com/saitokazumasa/tabisketch/pull/141/commits/5d074a67a262620d5e354d28467a5c11d049e9a4)

2024-12-03 02:00 UTC, saitokazumasa commented on src/main/resources/static/js/modal.js
> +    }
サンクス

2024-12-03 02:00 UTC, saitokazumasa commented on src/main/resources/static/js/modal.js
> +            setTimeout(() => document.activeElement.blur(), 0)
サンクス

2024-12-03 02:02 UTC, saitokazumasa commented on src/main/resources/static/js/modal.js
> +            const form = new ModalForm();
サンクス！
今はいいんだけど、正直これ何やってるのか詳しく読まないとあんまりわからないから
概要コメント欲しいなって思った！

※概要コメントっていうのは行のまとまりごとに何やってるかの概要を説明するコメント
```
// ここで〇〇している、みたいな
fragment.addFragment();
modal.closeModal();
placeNum.increment();
```

2024-12-03 02:02 UTC, saitokazumasa commented on src/main/resources/static/js/modal.js
> +InitModal();
サンクス！

2024-12-03 02:03 UTC, saitokazumasa commented
https://github.com/saitokazumasa/tabisketch/pull/141#discussion_r1866878244

> 今はいいんだけど、正直これ何やってるのか詳しく読まないとあんまりわからないから
>概要コメント欲しいなって思った！
>
>※概要コメントっていうのは行のまとまりごとに何やってるかの概要を説明するコメント
> ```
> // ここで〇〇している、みたいな
> fragment.addFragment();
> modal.closeModal();
> placeNum.increment();
> ```

2024-12-03 02:04 UTC, saitokazumasa approved these changes
LGTM! いっぱい修正してくれてありがとう！

2024-12-03 02:05 UTC, merged