チェックボックスとラジオボタンの作成
saitokazumasa/tabisketch pull request #148
Opened 2024-12-02 02:26 UTC by BruinJr

## 概要

close #147 

- チェックボックスをクリックしたときの動きを追加
- ラジオボタンをクリックしたときの動きを追加
### スクリーンショット

![image](https://github.com/user-attachments/assets/5a8e6650-f3d8-44fb-a92c-9ad18231afb9)

2024-12-02 02:52 UTC, t-dounoma requested changes

2024-12-02 02:52 UTC, t-dounoma commented on src/main/resources/static/js/svgcheckbox.js
jsのファイル名が全て小文字なの見にくい
lowerCamelで

2024-12-02 02:52 UTC, t-dounoma commented on src/main/resources/static/js/svgradiobutton.js
ここも同じくかな

2024-12-02 02:53 UTC, saitokazumasa requested changes

2024-12-02 02:53 UTC, saitokazumasa commented on src/main/resources/static/js/svgcheckbox.js
> +            this.init();
早期リターン推奨
```suggestion
        if (!this.checkbox || !this.targetElement) return;
        this.init();
```

2024-12-02 02:53 UTC, saitokazumasa commented on src/main/resources/static/js/svgcheckbox.js
> +        }
こちらも
```suggestion
        if (this.checkbox.checked) {
            this.targetElement.classList.remove('fill-label');
            return;
        }
        
        this.targetElement.classList.add('fill-label');
```

2024-12-02 02:53 UTC, saitokazumasa commented on src/main/resources/static/js/svgcheckbox.js
> +const managers = [
この変数はどういう意味で`managers`にしたの？

2024-12-02 02:53 UTC, saitokazumasa commented on src/main/resources/static/js/svgradiobutton.js
> +class RadioButtonManager {
`RadioButtonManager` でなく、ラジオボタン単体のクラスにした方が良い

2024-12-02 02:53 UTC, saitokazumasa commented on src/main/resources/static/js/svgradiobutton.js
> +        });
やるならこんな感じかな
動確してないからいい感じに書き換えてね
```suggestion
class RadioButton {
    #element;
    #svgElement

    constructor(element, svgElement) {
        this.#element = element;
        this.#svgElement = svgElement;
        this.#element.addEventListener('change', () => this.onChanged());
        init();
    }
    
    onChanged() {
        if (radio.checked) {
            this.#svgElement.classList.remove('fill-label');
            return;
        }
        this.#svgElement.classList.add('fill-label');
    }
}


class RadioButtonList {
    #values = new Array(0);
    
    constructor(radioGroupName, svgClass) {
        const radioButtonElements = document.querySelectorAll(`input[name="${radioGroupName}"]`);
        const svgElements = document.querySelectorAll(`.${svgClass}`);
        
        if (this.#values .length <= 0 || svgElements .length <= 0) return;
        
        this.radioButtons.forEach((radioButton, index) => {
            const radioButton = new RadioButton(radioButton, svgElements[index]);
            this.#values.push(radioButton);
        });
    }
```

2024-12-02 02:53 UTC, t-dounoma requested changes
コンフリクトの解消よろしく

2024-12-02 03:01 UTC, t-dounoma requested changes
これjsファイルどうやって呼び出してる？
htmlにも書いてないし、script.htmlにも追加ないみたいだけど

2024-12-04 02:22 UTC, BruinJr commented on src/main/resources/static/js/svgcheckbox.js
[f6332e8](https://github.com/saitokazumasa/tabisketch/pull/148/commits/f6332e884833c48d74c2eea5b465c7cebf8cb4e5)
修正しました。

2024-12-04 02:22 UTC, BruinJr commented on src/main/resources/static/js/svgradiobutton.js
[f6332e8](https://github.com/saitokazumasa/tabisketch/pull/148/commits/f6332e884833c48d74c2eea5b465c7cebf8cb4e5)
修正しました。

2024-12-04 02:30 UTC, BruinJr commented on src/main/resources/static/js/svgcheckbox.js
> +const managers = [
[1266a55](https://github.com/saitokazumasa/tabisketch/pull/148/commits/1266a555781ee6d71565b5f145b75e796d60da3e)
参考にしたサイトの変数名のまま使っていたので変数名 `checkboxIdList` に変更しました。

2024-12-04 02:31 UTC, BruinJr commented on src/main/resources/static/js/svgcheckbox.js
> +            this.init();
[1cae343](https://github.com/saitokazumasa/tabisketch/pull/148/commits/1cae343fd9839b7fda162fdbcccd15d22eb4f476)
修正しました。

2024-12-04 02:31 UTC, BruinJr commented on src/main/resources/static/js/svgcheckbox.js
> +        }
[1cae343](https://github.com/saitokazumasa/tabisketch/pull/148/commits/1cae343fd9839b7fda162fdbcccd15d22eb4f476)
修正しました。

2024-12-04 02:33 UTC, BruinJr commented on src/main/resources/static/js/svgradiobutton.js
> +        });
[9d45df4](https://github.com/saitokazumasa/tabisketch/pull/148/commits/9d45df488e3e8a190933fc1105c7059edefa7b17)
[4666bf8](https://github.com/saitokazumasa/tabisketch/pull/148/commits/4666bf82a66453fa1653e9218b678438bfce66f8)
修正しました。

2024-12-04 02:48 UTC, saitokazumasa commented on src/main/resources/static/js/svgcheckbox.js
> +            this.init();
サンクス

2024-12-04 02:48 UTC, saitokazumasa commented on src/main/resources/static/js/svgcheckbox.js
> +        }
サンクス

2024-12-04 02:50 UTC, saitokazumasa commented on src/main/resources/static/js/svgcheckbox.js
> +const managers = [
うーん、これって ToggleCheckbox は何のためのクラスなの？
何をするクラスなの？

2024-12-04 02:59 UTC, BruinJr commented on src/main/resources/static/js/svgcheckbox.js
> +const managers = [
このクラスはcheckboxがクリックされたら、svg画像の色を変えるためのものです

2024-12-04 03:00 UTC, t-dounoma approved these changes
修正ありがとう！
LGTM

2024-12-04 03:01 UTC, saitokazumasa commented on src/main/resources/static/js/svgradiobutton.js
> +        });
RadioButtonListがRadioButtonに依存している方向性で、
RadioButtonがRadioButtonに依存する書き方は良くないかな。
依存の方向を統一して欲しい。一般的には大きい概念から小さい概念に依存するとすっきりするかも。
※めっちゃ要約して書くと、RadioButtonでRadioButtonListを操作しないでってこと
```
class RadioButton {
    #parentList;
    constructor() {
        this.#element.addEventListener('change', () => this.#parentList.checkAll()); // NG
    }
}
```

多分RadioButtonのどれかが操作されたときに動かす関数っていう意味で`onChecked()`にしたんだと思うんだけど、
これってRadioButtonの`onChanged()`が動いたときに一緒に動かしているだけで、実際は変更に伴って動いてる関数ではないよね。
そういうときは`on○○`より、こういう操作をしている、っていう関数名にしよう。
```
class RadioButtonList {
    onChecked() {
        this.#values.forEach((radioButton) => {
            radioButton.onChanged();
        });
}
```

2024-12-04 03:04 UTC, saitokazumasa commented on src/main/resources/static/js/svgcheckbox.js
> +const managers = [
だよね、てことはcheckboxIdListではなくない？
あとそういうためのクラスなら、`ToggleCheckbox`よりも「svg画像の色を変えるクラス」っていう名づけにした方が良いね。

2024-12-04 03:06 UTC, saitokazumasa commented on src/main/resources/static/js/svgradiobutton.js
> +class RadioButtonManager {
ここで修正されたためOK
https://github.com/saitokazumasa/tabisketch/pull/148/commits/9d45df488e3e8a190933fc1105c7059edefa7b17

2024-12-04 03:12 UTC, BruinJr commented on src/main/resources/static/js/svgcheckbox.js
> +const managers = [
checkboxIdList -> svgIdList
ToggleCheckbox -> ChangeSVGColor
でどうでしょうか？

2024-12-04 03:17 UTC, saitokazumasa commented on src/main/resources/static/js/svgcheckbox.js
> +const managers = [
このリスト、「svg画像の色を変えるクラス」のリストならid関係ないのでは。

> ToggleCheckbox -> ChangeSVGColor

これはいいと思うよ！
Javaの方では結構やってるんだけど、
動詞+名詞のクラス名にして関数を`execute()`(実行)だけにすると、その機能だけのクラスができあがる。
こうすると何のためのクラスなのかもわかりやすいし、大きいクラスにならないからおすすめ。

2024-12-05 02:57 UTC, BruinJr commented on src/main/resources/static/js/svgcheckbox.js
> +const managers = [
[a990f83](https://github.com/saitokazumasa/tabisketch/pull/148/commits/a990f83c78f32b3685a11a9b9a845dd11a5535a6)
上記の内容を踏まえて修正しました。

2024-12-05 02:57 UTC, BruinJr commented on src/main/resources/static/js/svgradiobutton.js
> +        });
[9a5bed8](https://github.com/saitokazumasa/tabisketch/pull/148/commits/9a5bed863f56e37200bd1ab90400d90a8e53cfe5)
修正しました。

2024-12-06 00:33 UTC, saitokazumasa commented on src/main/resources/static/js/svgcheckbox.js
> +const managers = [
サンクス

2024-12-06 00:36 UTC, saitokazumasa commented on src/main/resources/static/js/svgradiobutton.js
> +        });
う～ん、変わってないかなぁ
依存の意味をもう一度調べてみて欲しいんだけど、そもそもRadioButtonがRadioButtonListをコンストラクタの引数として受け取って保持している時点で逆方向に依存しちゃってるんだよね。

2024-12-11 03:26 UTC, BruinJr commented on src/main/resources/static/js/svgradiobutton.js
> +        });
[88b40b7](https://github.com/saitokazumasa/tabisketch/pull/148/commits/88b40b7568a82c17e3edcd284e511449cf6ba885)
かなり変えちゃいましたが修正しました。

2024-12-11 07:25 UTC, saitokazumasa requested changes

2024-12-11 07:25 UTC, saitokazumasa commented on src/main/resources/static/js/svgRadioButton.js
> +            }
早期リターン推奨です。

2024-12-11 07:25 UTC, saitokazumasa commented on src/main/resources/static/js/svgRadioButton.js
>  class RadioButton {
これってRadioButtonというかRadioButtonListじゃないっすか？

2024-12-11 07:25 UTC, saitokazumasa commented on src/main/resources/static/js/svgradiobutton.js
> +        });
サンクス！
別コメントしたため、このコメントは解決。

2024-12-11 07:39 UTC, BruinJr commented on src/main/resources/static/js/svgRadioButton.js
> +            }
[7692828](https://github.com/saitokazumasa/tabisketch/pull/148/commits/769282819d7265f2363be50299aaa07cdd9d5ff5)
修正しました。

2024-12-11 07:51 UTC, saitokazumasa commented on src/main/resources/static/js/svgRadioButton.js
> +            }
その上もやね。

2024-12-11 07:51 UTC, saitokazumasa commented on src/main/resources/static/js/svgRadioButton.js
>  class RadioButton {
サンクス！

2024-12-11 08:18 UTC, saitokazumasa commented on src/main/resources/static/js/svgRadioButton.js
> +            }
サンクス！

2024-12-11 08:18 UTC, saitokazumasa approved these changes
とても良い感じ
LGTM

2024-12-11 08:18 UTC, merged