Create edit user controller test
saitokazumasa/tabisketch pull request #166
Opened 2024-12-05 02:51 UTC by imanoari

## 概要

closeしない  #155 

- EditUserControllerのテスト修正

### スクリーンショット

2024-12-06 01:34 UTC, saitokazumasa requested changes

2024-12-06 01:34 UTC, saitokazumasa commented on src/test/java/com/tabisketch/controller/EditUserControllerTest.java
> +    @ValueSource(strings = {"sample2@example.com"})
sample2 にする必要はないかな、`sample@example.com`でよし
テストデータはなるべく余計な情報を含めないように。

2024-12-06 01:34 UTC, saitokazumasa commented on src/test/java/com/tabisketch/controller/EditUserControllerTest.java
> +    public void getが動作するか(final String mail) throws Exception {
引数でmailは送らない！
`@WithMockUser()` でテストに使うログインユーザーの情報を設定してテストして。

2024-12-06 01:35 UTC, saitokazumasa requested changes

2024-12-06 01:35 UTC, saitokazumasa commented on src/test/java/com/tabisketch/controller/EditUserControllerTest.java
> +                .andExpect(MockMvcResultMatchers.model().attributeExists("user"));
細かいけど、書く順番統一してね。
気持ちの問題だけでなく、ぱっと見でわかりやすくなるから。

2024-12-06 01:35 UTC, saitokazumasa commented on src/test/java/com/tabisketch/controller/EditUserControllerTest.java
> +                .andExpect(MockMvcResultMatchers.model().attributeExists("user"));
Attributeが存在するかだけでなく、Attributeの中身も検証してね。

2024-12-06 01:35 UTC, imanoari commented on src/test/java/com/tabisketch/controller/EditUserControllerTest.java
> +    @ValueSource(strings = {"sample2@example.com"})
気付きませんでした。ありがとうございます
修正しました
https://github.com/saitokazumasa/tabisketch/pull/166/commits/9e944bd1e3f1ef68777a8c19fa6f29178890232c

2024-12-06 01:50 UTC, imanoari commented on src/test/java/com/tabisketch/controller/EditUserControllerTest.java
> +    public void getが動作するか(final String mail) throws Exception {
一応修正入れました。確認なんだけどMockUserの中に入ってる情報でログインした状態作ってる的な認識であってる？
https://github.com/saitokazumasa/tabisketch/pull/166/commits/5dc42101e832dd651d6ae8324116a73876840eef

2024-12-06 01:51 UTC, saitokazumasa commented on src/test/java/com/tabisketch/controller/EditUserControllerTest.java
> +    @ValueSource(strings = {"sample2@example.com"})
サンクス

2024-12-06 01:52 UTC, saitokazumasa commented on src/test/java/com/tabisketch/controller/EditUserControllerTest.java
> +    public void getが動作するか(final String mail) throws Exception {
引数残ってるよ。

> MockUserの中に入ってる情報でログインした状態作ってる的な認識であってる？
あってる。

2024-12-06 01:56 UTC, imanoari commented on src/test/java/com/tabisketch/controller/EditUserControllerTest.java
> +    public void getが動作するか(final String mail) throws Exception {
あ、ごめんなさい。修正しました
https://github.com/saitokazumasa/tabisketch/pull/166/commits/ebb953e1318e68379f210f57fa1166f5d49a0b17

2024-12-06 02:05 UTC, saitokazumasa commented on src/test/java/com/tabisketch/controller/EditUserControllerTest.java
> +    public void getが動作するか(final String mail) throws Exception {
引数残ってるよ

2024-12-06 02:14 UTC, imanoari commented on src/test/java/com/tabisketch/controller/EditUserControllerTest.java
> +                .andExpect(MockMvcResultMatchers.model().attributeExists("user"));
修正しました。
https://github.com/saitokazumasa/tabisketch/pull/166/commits/756f27e8b1ccb64a37da6f6b7ce65532c06e2603

2024-12-06 02:19 UTC, imanoari commented on src/test/java/com/tabisketch/controller/EditUserControllerTest.java
> +    public void getが動作するか(final String mail) throws Exception {
本当にすみません。修正しました
https://github.com/saitokazumasa/tabisketch/pull/166/commits/1d076c15389f8dcd5204e1bd941e09e16a34863a

2024-12-06 02:48 UTC, imanoari commented on src/test/java/com/tabisketch/controller/EditUserControllerTest.java
> +                .andExpect(MockMvcResultMatchers.model().attributeExists("user"));
書き方あってますか…？
https://github.com/saitokazumasa/tabisketch/pull/166/commits/9dfbfd2fe42c016e0707ebae468eef00f6a2c4c9

2024-12-09 00:32 UTC, closed without merging

2024-12-09 01:31 UTC, imanoari commented
別PRに移すのでクローズします