[WIP] 経路作成画面のデザインとスクリプト作成
saitokazumasa/tabisketch pull request #167
Opened 2024-12-05 03:35 UTC by t-dounoma

## 概要

close #108 

- デザインを作成(以下の動画を参照)
- 入力値チェックのスクリプトを作成
- sp版、pc版のmapを作成

### スクリーンショット

pc版
https://github.com/user-attachments/assets/595cf62f-449f-4a79-ab80-86ab91d9a788

sp版
https://github.com/user-attachments/assets/f96725cc-73e7-491c-8367-1a7fffdf4452

2024-12-09 01:18 UTC, ishiki11 commented
jsのsessionStorage使うなら取得方法違うかも
以下参考に
https://developer.mozilla.org/ja/docs/Web/API/Window/sessionStorage

2024-12-09 01:21 UTC, ishiki11 reviewed
jsのsessionStorage使うなら取得方法違うかも
以下参考に
https://developer.mozilla.org/ja/docs/Web/API/Window/sessionStorage

map.jsクラス化できそう

2024-12-09 01:34 UTC, ishiki11 submitted a review, later dismissed
デザインはいいと思います
LGTM

2024-12-09 01:45 UTC, saitokazumasa requested changes

2024-12-09 01:45 UTC, saitokazumasa commented on src/main/resources/static/js/checkSession.js
> +});
この辺クラス化した方が良いかも

2024-12-09 01:45 UTC, saitokazumasa commented on src/main/resources/static/js/map.js
> +window.onload = initMap;
この辺もクラス化した方が良いかも

2024-12-09 02:36 UTC, t-dounoma commented on src/main/resources/static/js/checkSession.js
> +});
対応しました
f6248970091638c8afe50782193f807e40cad6d9
lintに対応できてなかったので以下でlintに対応ずみ
4842ceb48d7dd12f9e067a71e3a442d8e9245744

2024-12-09 02:37 UTC, t-dounoma commented on src/main/resources/static/js/map.js
> +window.onload = initMap;
同じくクラスに修正しました
a4fb566e622f8de0d11836c989ca509ffd0f8f0e
lintに対応はchecksessionとおなじcommit
4842ceb48d7dd12f9e067a71e3a442d8e9245744

2024-12-09 05:19 UTC, saitokazumasa commented on src/main/resources/static/js/checkSession.js
> +});
サンクス

2024-12-09 05:22 UTC, saitokazumasa commented on src/main/resources/static/js/map.js
> +window.onload = initMap;
`○○Manager` ていうクラス名にすると肥大化しがち（Mapに関すること全て書いていいクラスなんだ！と他の人が思う）なので、Mapだけでも良いし、もっと良い名前があったらそっちでも良い。
とりあえずクラスが小さくなるような名前にしてみて。

2024-12-09 05:47 UTC, t-dounoma commented on src/main/resources/static/js/map.js
> +window.onload = initMap;
りょかい🫡

2024-12-10 00:37 UTC, t-dounoma commented on src/main/resources/static/js/map.js
> +window.onload = initMap;
他にいい名前思いつかなかったし、長くなってもって感じだったからそのままMapクラスに修正してます
bbf2dafa58d59d842f09af1cbcb0c0a10e2d4d37

2024-12-10 00:44 UTC, saitokazumasa commented on src/main/resources/static/js/map.js
> +window.onload = initMap;
サンクス

2024-12-10 00:45 UTC, saitokazumasa requested changes

2024-12-10 00:45 UTC, saitokazumasa commented on src/main/resources/static/js/map.js
> +const mapManager = new Map();
修正漏れ発見

2024-12-10 00:45 UTC, saitokazumasa commented on src/main/resources/static/js/checkSession.js
> +class SessionManager {
ここも `Session` で良さそう

2024-12-10 00:56 UTC, t-dounoma commented on src/main/resources/static/js/map.js
> +const mapManager = new Map();
失念しておりました修正します

2024-12-10 00:56 UTC, t-dounoma commented on src/main/resources/static/js/checkSession.js
> +class SessionManager {
おけす

2024-12-10 01:05 UTC, t-dounoma commented on src/main/resources/static/js/map.js
> +const mapManager = new Map();
修正いたしました
869dacb294f5ae6fb56ceeefc7cb2feae35806ea

2024-12-10 01:05 UTC, t-dounoma commented on src/main/resources/static/js/checkSession.js
> +class SessionManager {
修正しました
869dacb294f5ae6fb56ceeefc7cb2feae35806ea

2024-12-10 01:57 UTC, saitokazumasa commented on src/main/resources/static/js/map.js
> +const mapManager = new Map();
サンクス

2024-12-10 01:57 UTC, saitokazumasa commented on src/main/resources/static/js/checkSession.js
> +class SessionManager {
サンクス

2024-12-10 01:58 UTC, saitokazumasa approved these changes
LGTM

2024-12-10 01:58 UTC, merged