Create header layout
saitokazumasa/tabisketch pull request #31
Opened 2024-11-11 03:18 UTC by BruinJr

![image](https://github.com/user-attachments/assets/7a3d38e5-4f65-4014-bdde-1570a67517d9)

行ったこと
- headerの作成
- デザインの追加

issue
Closes https://github.com/saitokazumasa/tabisketch/issues/19

やらなければいけないこと
thymeleafの適用
hederの画像を追加

2024-11-12 00:30 UTC, saitokazumasa commented on pom.xml
> +        </dependency>
これって何に使ってるの？

2024-11-12 01:06 UTC, t-dounoma commented
marginの指定が全部mr-xxでやってるけどそれだと右方向のmarginにしかならない、mx-xxでやれば横方向のmarginにできるからそっちの方が綺麗かな

2024-11-12 01:21 UTC, t-dounoma requested changes

2024-11-12 01:46 UTC, BruinJr commented on pom.xml
> +        </dependency>
ローカルで使ってたものなので後で消します。

2024-11-13 02:25 UTC, saitokazumasa commented on pom.xml
> +        </dependency>
削除完了したらもう一度返信お願いします。

2024-11-13 05:00 UTC, closed without merging

2024-11-13 05:00 UTC, BruinJr commented
ブランチ名を変更したためクローズ