layoutのheaderを作成
saitokazumasa/tabisketch pull request #36
Opened 2024-11-13 05:24 UTC by BruinJr

## 概要

close　#19 

 - pc画面のheaderを作成
 - スマホ画面のheaderを作成
 
Tailwind hamburger menus.
`npm install tailwind-hamburgers -S`

### スクリーンショット

pc画面
![image](https://github.com/user-attachments/assets/b5f91840-720c-46c1-9740-31b799de77ed)

スマホ画面
![image](https://github.com/user-attachments/assets/caceed24-568c-4010-a159-56037ff63242)
![image](https://github.com/user-attachments/assets/c08475c2-92ca-4c78-9acd-b3f73587fcd9)

2024-11-13 06:02 UTC, t-dounoma requested changes
デフォルトのフォントカラーが"1E1E1E"を使ってるからtailwind.config.jsに
```"default" : "#1E1E1E",```
を書いてフォントカラーをつけてほし

2024-11-14 02:33 UTC, t-dounoma requested changes

2024-11-14 02:33 UTC, t-dounoma commented on tailwind.config.js
> +                'title': '32px',
単位はremで統一がいい
32px→2remだね

2024-11-14 02:43 UTC, t-dounoma requested changes

2024-11-14 02:43 UTC, t-dounoma commented on src/main/resources/templates/fragment/header.html
> +</th:block>
ここの部分はth:blockで囲んであるし、別ファイルにしたほうがいいと思う。
ってかこれ他で呼び出すことある?

2024-11-14 02:59 UTC, t-dounoma commented
> デフォルトのフォントカラーが"1E1E1E"を使ってるからtailwind.config.jsに `"default" : "#1E1E1E",` を書いてフォントカラーをつけてほし

mainにtailwind.configマージしてもらったからそれ参照にフォントカラーの適用を行って欲しい
text-defaultで適用される

2024-11-14 04:56 UTC, saitokazumasa requested changes

2024-11-14 04:56 UTC, saitokazumasa commented on pom.xml
> -</project>
余計な変更を含めないようにお願いします！

2024-11-14 04:56 UTC, saitokazumasa commented on src/main/resources/templates/fragment/header.html
> +</script>
JSべた書きは嫌です！
JSファイルにして欲しいです。

2024-11-14 04:56 UTC, saitokazumasa commented on src/main/resources/templates/fragment/header.html
> +    const tham = document.querySelector(".tham");
`tham` ってどういう意味ですか？

2024-11-14 05:03 UTC, t-dounoma requested changes
![image](https://github.com/user-attachments/assets/129d3337-0e63-4d57-9263-264ab0a3d249)
デスクトップ画面で開いてもハンバーガーメニューが表示されてるんだけどこれは今の段階で正常な動作？

2024-11-14 05:05 UTC, t-dounoma commented on tailwind.config.js
> +                'title': '32px',
4remっぽいサーセン

2024-11-15 01:55 UTC, BruinJr commented on src/main/resources/templates/fragment/header.html
> +</script>
変更しました

2024-11-15 02:01 UTC, BruinJr commented on src/main/resources/templates/fragment/header.html
> +    const tham = document.querySelector(".tham");
pluginから直接持ってたものです。
![image](https://github.com/user-attachments/assets/ed33a40f-eea9-4b10-a029-f2161cf805cb)

2024-11-15 02:06 UTC, BruinJr commented on tailwind.config.js
> +                'title': '32px',
変更しました。

2024-11-15 02:11 UTC, BruinJr commented on pom.xml
> -</project>
次から気を付けます...

2024-11-15 02:15 UTC, t-dounoma commented on tailwind.config.js
> +                'title': '32px',
commitのversion貼ってね
0b6174b684ad762c8bc592b6806204765331d8b4
ここはLGTM

2024-11-15 02:46 UTC, BruinJr commented on src/main/resources/templates/fragment/header.html
> +</th:block>
jsファイルへ移動しました。
[74b714c](https://github.com/saitokazumasa/tabisketch/pull/36/commits/74b714c734106ed820239a42801c4e8a5da7e758)

2024-11-15 03:12 UTC, t-dounoma commented on src/main/resources/templates/fragment/header.html
> +</th:block>
実行確認できてないからなんとも言えないんだけどheaderでscript読み込んでる？

2024-11-15 03:14 UTC, t-dounoma commented
> > デフォルトのフォントカラーが"1E1E1E"を使ってるからtailwind.config.jsに `"default" : "#1E1E1E",` を書いてフォントカラーをつけてほし
> 
> mainにtailwind.configマージしてもらったからそれ参照にフォントカラーの適用を行って欲しい text-defaultで適用される

一つ一つフォント適用するのめんどいんだったらheadに全体適用でtext-defaultをつけるか
headerでは変更しなくていよ

2024-11-15 03:25 UTC, saitokazumasa commented on src/main/resources/templates/fragment/header.html
> +</script>
これ動作します？

2024-11-15 03:26 UTC, BruinJr commented on src/main/resources/templates/fragment/header.html
> +</script>
Tailwind hamburger menus.
npm install tailwind-hamburgers -S

これしないと動作しないです

2024-11-15 03:28 UTC, saitokazumasa commented on src/main/resources/templates/fragment/header.html
> +    const tham = document.querySelector(".tham");
tailwindcss で既に用意されているクラスってこと？
それとも tailwind css が作った、任意のクラス（js用に作られただけのクラス）ってこと？

2024-11-15 03:28 UTC, saitokazumasa commented on pom.xml
> -</project>
これは修正した？

2024-11-15 03:42 UTC, BruinJr commented on src/main/resources/templates/fragment/header.html
> +</th:block>
呼び出せるようにしました
[99a9760](https://github.com/saitokazumasa/tabisketch/pull/36/commits/99a97600b70b0a432bafcf194a2c6141281399ba)
[2726577](https://github.com/saitokazumasa/tabisketch/pull/36/commits/272657743245cdf835d83505f6681ea34da9c4db)

2024-11-15 03:43 UTC, BruinJr commented on src/main/resources/templates/fragment/header.html
> +    const tham = document.querySelector(".tham");
tailwind.cssのプラグインで用意されているものでございます。

2024-11-15 03:45 UTC, BruinJr commented on pom.xml
> -</project>
修正しました。
[0ce9759](https://github.com/saitokazumasa/tabisketch/pull/36/commits/0ce975982758eff1bc621472759f27001ce5afe7)

2024-11-15 11:03 UTC, t-dounoma commented on src/main/resources/templates/fragment/header.html
> +</th:block>
ごめん、説明不足だった
header.htmlでstatic/js/header.jsを読み込む処理がないから、headerをページでlayoutとして読み込んだ時に、処理が動かないコードになっちゃってるってこと
画面録画してみたみたんだけど、こんな感じで、ハンバーガーメニューのとこを押しても動作しなくないかな

https://github.com/user-attachments/assets/4d30b3ed-4e2d-49a4-8d37-2f2da69d6deb

2024-11-15 12:13 UTC, t-dounoma commented on src/main/resources/templates/fragment/header.html
> +</th:block>
りかいりかい
LGTM

2024-11-18 00:33 UTC, t-dounoma approved these changes
dounomae-LGTM

2024-11-18 01:00 UTC, saitokazumasa commented on src/main/resources/templates/fragment/header.html
> +    const tham = document.querySelector(".tham");
OK!　あざます！

2024-11-18 01:01 UTC, saitokazumasa commented on src/main/resources/templates/fragment/header.html
> +</script>
あ、いや js ファイルをどこで読み込んでるのかな～っていう意味での質問だった

2024-11-18 01:02 UTC, saitokazumasa commented on pom.xml
> -</project>
なんか header のクラス書き変わってるけどだいじょぶそ？

2024-11-18 01:05 UTC, BruinJr commented on src/main/resources/templates/fragment/header.html
> +</script>
ここは石木くんと話し合ってページごとでjsを呼び出そうって話になりました。
ログインページだったらログインページにheader.jsを呼び出すscriptタグを入れるみたいな感じです。

2024-11-18 01:06 UTC, saitokazumasa commented on src/main/resources/templates/fragment/header.html
> +</script>
おｋです！ありがとうございます。

2024-11-18 01:08 UTC, saitokazumasa commented on pom.xml
> -</project>
大丈夫っぽいのでOK！

2024-11-18 01:09 UTC, saitokazumasa approved these changes
LGTM

2024-11-18 01:09 UTC, merged