footerのレイアウトを作成
saitokazumasa/tabisketch pull request #40
Opened 2024-11-14 03:21 UTC by BruinJr

## 概要

close #20 

- footerのレイアウトを作成
- レスポンシブデザイン

### スクリーンショット

![image](https://github.com/user-attachments/assets/b3cc0bce-9723-44af-8fd1-613033717c37)
![image](https://github.com/user-attachments/assets/47cbe71f-5f71-497a-a7bf-1b22665ad085)

2024-11-14 04:50 UTC, saitokazumasa approved these changes
Tailwindについてはフロントチームに任せる。
他はOK

2024-11-15 00:40 UTC, t-dounoma requested changes

2024-11-15 00:40 UTC, t-dounoma commented on src/main/resources/templates/fragment/footer.html
> +<footer class="flex border-2 w-full h-7 md:h-12 text-base md:text-xl items-center justify-center">
spを使用して

2024-11-15 10:20 UTC, t-dounoma commented on src/main/resources/templates/fragment/footer.html
> +<footer class="flex border-2 w-full h-7 md:h-12 text-base md:text-xl items-center justify-center">
smだったみたい
変更はそれだけだからそれ出来たらapproveできるよ

2024-11-18 00:41 UTC, BruinJr commented on src/main/resources/templates/fragment/footer.html
> +<footer class="flex border-2 w-full h-7 md:h-12 text-base md:text-xl items-center justify-center">
変更しました
[98931de](https://github.com/saitokazumasa/tabisketch/pull/40/commits/98931de3eb3a33b7f2f79c1cc564c0bf18827322)

2024-11-18 01:43 UTC, t-dounoma commented on src/main/resources/templates/fragment/footer.html
> +<footer class="flex border-2 w-full h-7 md:h-12 text-base md:text-xl items-center justify-center">
ok

2024-11-18 01:44 UTC, t-dounoma approved these changes

2024-11-18 01:45 UTC, merged