メールアドレス編集画面の作成
saitokazumasa/tabisketch pull request #90
Opened 2024-11-21 03:23 UTC by ishiki11

## 概要

close #88 

- user/edit/mail.htmlを作成
- head,header,footer,headerのscriptフラグメントの呼び出し
- レスポンシブ表示

### スクリーンショット

![image](https://github.com/user-attachments/assets/bb27312a-7739-4477-bd5d-87f0d685c23a)

2024-11-21 06:09 UTC, saitokazumasa requested changes

2024-11-21 06:09 UTC, saitokazumasa commented on src/main/resources/templates/user/edit/mail.html
> +            <input id="mail" type="email" required class="w-full input"/>
「新しいメールアドレスを入力」の方がわかりやすいと思った！

2024-11-21 06:10 UTC, ishiki11 commented on src/main/resources/templates/user/edit/mail.html
> +            <input id="mail" type="email" required class="w-full input"/>
りょ

2024-11-22 00:37 UTC, ishiki11 commented on src/main/resources/templates/user/edit/mail.html
> +            <input id="mail" type="email" required class="w-full input"/>
「新しいメールアドレス」にしました

2024-11-22 01:01 UTC, saitokazumasa commented on src/main/resources/templates/user/edit/mail.html
> +            <input id="mail" type="email" required class="w-full input"/>
コミットのURL貼ってください

2024-11-22 01:10 UTC, ishiki11 commented on src/main/resources/templates/user/edit/mail.html
> +            <input id="mail" type="email" required class="w-full input"/>
https://github.com/saitokazumasa/tabisketch/pull/90/commits/053c27b3da660414dc0b09b94a8c7124e3947868

2024-11-22 01:23 UTC, saitokazumasa commented on src/main/resources/templates/user/edit/mail.html
> +            <input id="mail" type="email" required class="w-full input"/>
ありがとうございま！

2024-11-22 01:24 UTC, saitokazumasa approved these changes
LGTM

2024-11-22 03:35 UTC, t-dounoma approved these changes
LGTM

2024-11-22 03:35 UTC, merged